version: '3.7'
services:
container_name: portainer
  server:
    image: portainer/portainer-ce:2.18.4@sha256:908d04d20e86f07a50b0f1a029a111b89aa3089b7fc7fdf68ec1c71b025f36cd
    command: '-H unix:///var/run/docker.sock'
    networks:
      - host
      ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data: null
