version: '2'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_IOBROKER_IP
      APP_PORT: 8081
  server:
    image: buanet/iobroker
      - VIRTUAL_PORT=8081
    networks:
      default:
        ipv4_address: $APP_IOBROKER_IP
    restart: always
    volumes:
      - iobrokerdata:/opt/iobroker