version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_IOBROKER_IP
      APP_PORT: 8081
  server:
    image: buanet/iobroker:v8.1.0@sha256:00722ae476426ed0f318945579a9564d1d156414d2545739d40bf889911ab933
      - VIRTUAL_PORT=8081
    networks:
      default:
        ipv4_address: $APP_IOBROKER_IP
    restart: always
    volumes:
      - iobrokerdata:/opt/iobroker
volumes:
  iobrokerdata: null
