version: '3.7'
services:
  server:
    image: buanet/iobroker:v8.1.0@sha256:50b8eb3434904c692e1ae186400bbf6025db87e310f166fe923e5037a7e15298
    network_mode: host
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data:/opt/iobroker
