version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_IOBROKER_IP
      APP_PORT: 8081
      PROXY_AUTH_ADD: 'false'
  server:
    image: iobroker/iobroker:v.8.1.0@sha256:042d541cf4a0e2a1eb832d055b6d3e68cc32a0cb4057dc0680a42318cd3c232b
    networks:
      default:
        ipv4_address: $APP_IOBROKER_IP
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data:/opt/iobroker