version: '3.7'

      services:
  iobroker:
    container_name: strs-iobroker
    server:
    image: iobroker/iobroker:v8.1.0@sha256:042d541cf4a0e2a1eb832d055b6d3e68cc32a0cb4057dc0680a42318cd3c232b
    restart: always
    ports:
      - "8081:8081"
     volumes:
      - iobrokerdata:/opt/iobroker
