version: '2'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_IOBROKER_IP
      APP_PORT: 8081
  server:
    image: buanet/iobroker:latest
    command: '-H unix:///var/run/docker.sock'
    environment:
      - VIRTUAL_PORT=8081
    networks:
      default:
        ipv4_address: $APP_IOBROKER_IP
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - iobrokerdata:/opt/iobroker
volumes:
  iobroker_data: null
