version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_IOBROKER_IP
      APP_PORT: 9981
      PROXY_AUTH_ADD: 'false'
  server:
    image: buanet/ioBroker.docker:v9.1.2@null
    command: '-H unix:///var/run/docker.sock'
    environment:
      - VIRTUAL_PORT=9981
    networks:
      default:
        ipv4_address: $APP_IOBROKER_IP
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data:/opt/iobroker
