version: '3.7'
services:
  server:
    image: iobroker/iobroker:v.8.1.0@sha256:042d541cf4a0e2a1eb832d055b6d3e68cc32a0cb4057dc0680a42318cd3c232b
    network_mode: host
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - ${APP_DATA_DIR}/data:/opt/iobroker
